import Head from 'next/head';
import * as React from 'react';
import { useRouter } from 'next/router';
import { Product } from '@/interfaces';
import { getProductsInCategory } from '@/helpers';

interface Props {
    products: Product[];
};

const ProductsInCategory: React.FC<Props> = ({ products }) => {
    const { pathname } = useRouter();
    return (
        <>
            <Head>
                <title>{pathname}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {products?.map(prod => {
                    return <div key={prod.id}>{prod.title}</div>;
                })}
                <br />
            </main>
        </>
    );
};

export default ProductsInCategory;

export async function getServerSideProps(context) {
    const products = await getProductsInCategory(context.params.category);

    if (!products?.length) return { redirect: { destination: '/', permanent: false, } };

    return { props: { products } };
}