import Head from 'next/head';
import * as React from 'react';
import { useRouter } from 'next/router';
import { Product } from '@/interfaces';
import { getCategories, getProductsInCategory } from '@/helpers';
import Link from 'next/link';
import { Layout } from '@/components';

interface Props {
    products: Product[];
    categories: string[];
};

const ProductsInCategory: React.FC<Props> = ({ products, categories }) => {
    const { pathname } = useRouter();

    return (
        <>
            <Head>
                <title>{pathname}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout categories={categories} >
                <main>
                    {products?.map(prod => {
                        return <Link key={prod.id} href={`/product/${encodeURIComponent(`${prod.title}-${prod.id}`)}`} legacyBehavior about={prod.title}>{prod.title}</Link>;
                    })}
                    <br />
                </main>
            </Layout>
        </>
    );
};

export default ProductsInCategory;

export async function getServerSideProps(context) {
    const categories = await getCategories();
    const products = await getProductsInCategory(context.params.category);

    if (!products?.length) return { redirect: { destination: '/', permanent: false, } };

    return { props: { products, categories } };
}